# Generated by Django 5.1.15 on 2026-05-11 13:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('ip_address', models.GenericIPAddressField(unique=True, verbose_name='Endereço IP')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Localização')),
                ('model_name', models.CharField(blank=True, max_length=100, verbose_name='Modelo')),
                ('protocol', models.CharField(choices=[('auto', 'Auto (SNMP → HTTP)'), ('snmp', 'SNMP'), ('http', 'HTTP/EWS')], default='auto', max_length=10, verbose_name='Protocolo')),
                ('snmp_community', models.CharField(default='public', max_length=50, verbose_name='Community SNMP')),
                ('is_color', models.BooleanField(default=False, verbose_name='Colorida')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Impressora',
                'verbose_name_plural': 'Impressoras',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TonerReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('black_pct', models.IntegerField(blank=True, null=True, verbose_name='Preto (%)')),
                ('cyan_pct', models.IntegerField(blank=True, null=True, verbose_name='Ciano (%)')),
                ('magenta_pct', models.IntegerField(blank=True, null=True, verbose_name='Magenta (%)')),
                ('yellow_pct', models.IntegerField(blank=True, null=True, verbose_name='Amarelo (%)')),
                ('protocol_used', models.CharField(blank=True, max_length=10, verbose_name='Protocolo usado')),
                ('success', models.BooleanField(default=False, verbose_name='Sucesso')),
                ('error_message', models.TextField(blank=True, verbose_name='Erro')),
                ('collected_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Coletado em')),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='printers.printer', verbose_name='Impressora')),
            ],
            options={
                'verbose_name': 'Leitura de Toner',
                'verbose_name_plural': 'Leituras de Toner',
                'ordering': ['-collected_at'],
                'indexes': [models.Index(fields=['printer', '-collected_at'], name='printers_to_printer_071648_idx')],
            },
        ),
    ]
