# Generated by Django 5.1.15 on 2026-05-26 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='contract_code',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Cód. Contrato'),
        ),
        migrations.AddField(
            model_name='printer',
            name='printer_type',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='printer',
            name='serial_number',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Nº Série'),
        ),
    ]
